[package]
name = "day17"
version = "0.1.0"
authors = ["Carlos GÃ¡lvez <carlosgalvezp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0"
